version: '3'
services:
  localstack:
    container_name: localstack
    image: localstack/localstack:0.11.6
    ports:
      - "4566-4599:4566-4599"
    environment:
      - SERVICES=sns,sqs
      - DATA_DIR=/tmp/localstack/data
    volumes:
      - './docker/localstack/init-scripts:/docker-entrypoint-initaws.d'
      - '/var/run/docker.sock:/var/run/docker.sock'
